export const heroData = [
  {
    id: 1,
    name: "Thunderbolt",
    superpower: "Electrokinesis",
    age: 28,
    picture: "/img/hero_images/lightning.png",
  },
  {
    id: 2,
    name: "Shadowmancer",
    superpower: "Shadow manipulation",
    age: 35,
    picture: "/img/hero_images/shadow.png",
  },
  {
    id: 3,
    name: "Quantum Girl",
    superpower: "Teleportation",
    age: 22,
    picture: "/img/hero_images/quantum-computing.png",
  },
  {
    id: 4,
    name: "Ironclad",
    superpower: "Invulnerability",
    age: 45,
    picture: "/img/hero_images/armour.png",
  },
  {
    id: 5,
    name: "Flora",
    superpower: "Plant control",
    age: 30,
    picture: "/img/hero_images/flower.png",
  },
  {
    id: 6,
    name: "Mindweaver",
    superpower: "Telepathy",
    age: 40,
    picture: "/img/hero_images/mind-map.png",
  },
  {
    id: 7,
    name: "Velocity",
    superpower: "Super speed",
    age: 25,
    picture: "/img/hero_images/arrows.png",
  },
  {
    id: 8,
    name: "Graviton",
    superpower: "Gravity manipulation",
    age: 50,
    picture: "/img/hero_images/astronaut.png",
  },
  {
    id: 9,
    name: "Chameleon",
    superpower: "Shape-shifting",
    age: 33,
    picture: "/img/hero_images/chameleon.png",
  },
  {
    id: 10,
    name: "Phoenix",
    superpower: "Resurrection and pyrokinesis",
    age: 200,
    picture: "/img/hero_images/phoenix.png",
  },
];
